### ISSUE TITLE
Map tiles not loading correctly. Cuts off words.

### ISSUE THREAD

**Issue by ghost** [scrivy/findme-frontend#10]
See picture. Words in the middle are cut off.
![2015-03-28](https://cloud.githubusercontent.com/assets/6632682/6884062/570a45e6-d58e-11e4-809e-d0b770995a44.jpg)

**Comment by scrivy** [comment]
flushed the tiles, didn't fix anything. think this is a problem with the guy who generated them

**Comment by ghost** [comment]
Is this the only free map we can use? What other options do we have?
